### ISSUE TITLE
The reprocess flow gives an error

### ISSUE THREAD

**Issue by sgiaccio** [slms4redd/slms-geobatch#43]
Log:

14:21:35,004 INFO  FileBasedEventGenerator$GBEventListener - Event: FILE_ADDED /var/stg_geobatch/input/reprocess/flow_6127171523169186469.xml
14:21:35,005 INFO  GenericActionService      - Instantiating action ReprocessAction
14:21:35,007 INFO  LoggingProgressListener   - Started [cbca9040-2ff3-4d76-8d21-6485e2f3a143]
14:21:35,007 INFO  LoggingProgressListener   - Progressing 10.0% -- Managing events [cbca9040-2ff3-4d76-8d21-6485e2f3a143]
14:21:35,007 INFO  LoggingProgressListener   - Progressing 20.0% -- Creating backup dir [cbca9040-2ff3-4d76-8d21-6485e2f3a143]
14:21:35,007 INFO  FileBasedEventConsumer    - [pool-5-thread-4]: new element retrieved from the MailBox.
14:21:35,008 INFO  LoggingProgressListener   - Progressing 30.0% -- Preprocessing event flow_6127171523169186469.xml [cbca9040-2ff3-4d76-8d21-6485e2f3a143]
14:21:35,008 INFO  FileBasedEventConsumer    - [pool-5-thread-4]: accepted file /var/stg_geobatch/input/reprocess/flow_6127171523169186469.xml
14:21:35,008 INFO  FileBasedEventConsumer    - [pool-5-thread-4]: new element processed.
14:21:35,008 INFO  LoggingProgressListener   - Progressing 50.0% -- Running actions [cbca9040-2ff3-4d76-8d21-6485e2f3a143]
14:21:35,009 INFO  LoggingProgressListener   - Progressing 0.0% -- Running Reprocess_Action(1/1) [cbca9040-2ff3-4d76-8d21-6485e2f3a143]
14:21:35,010 INFO  GeoStoreFacade            - Searching StatsDef forest_cover_stats
14:21:35,269 INFO  ReprocessAction           - Starting reprocessing StatsDef 'forest_cover_stats'
14:21:35,270 INFO  LoggingProgressListener   - Progressing 0.0% -- Starting reprocessing StatsDef 'forest_cover_stats' [Reprocess_Action]
14:21:35,270 ERROR UNREDDResource            - Bad attribute name Attribute[id is null, name=Layer, textValue=forest_cover, type=STRING] for class UNREDDStatsDef
14:21:35,270 WARN  ReprocessAction           - No layers defined for StatsDef 'forest_cover_stats'
14:21:35,270 INFO  ReprocessAction           - Reprocessing completed on StatsDef 'forest_cover_stats'
14:21:35,270 INFO  LoggingProgressListener   - Progressing 50.0% -- Reprocessing completed on StatsDef 'forest_cover_stats' [Reprocess_Action]
14:21:35,351 INFO  ReprocessAction           - Starting reprocessing ChartScripts
14:21:35,351 INFO  LoggingProgressListener   - Progressing 50.0% -- Starting reprocessing ChartScripts [Reprocess_Action]
14:21:35,351 INFO  FlowUtil                  - Running 0 scripts...
14:21:35,352 INFO  ReprocessAction           - Reprocessing ChartScripts completed
14:21:35,352 INFO  LoggingProgressListener   - Completed [Reprocess_Action]
14:21:35,352 INFO  BaseEventConsumer         - There are 1 events left in the queue after last action (Reprocess_Action)
14:21:35,352 INFO  LoggingProgressListener   - Progressing 100.0% -- Completed [cbca9040-2ff3-4d76-8d21-6485e2f3a143]
14:21:35,352 INFO  FileBasedEventConsumer    - pool-5-thread-4 DONE!
14:21:35,353 INFO  LoggingProgressListener   - Completed [cbca9040-2ff3-4d76-8d21-6485e2f3a143]

**Comment by Damianofds** [comment]
see this https://github.com/slms4redd/utils/pull/39
