### ISSUE TITLE
Error with the geobatch rasterising process

### ISSUE THREAD

**Issue by sgiaccio** [slms4redd/slms-geobatch#44]
Sample log:

14:50:30,964 ERROR BaseEventConsumer         - Error while rasterizing /var/stg_geobatch/temp/ingestionFlow/20150610-144955-007/0_ingestionFlow/unzip/data/forest_cover_2002.shp: Unable to process the input file: Expression NODATA is undefined on line 21, column 15 in gdalrasterize.xml.
14:50:30,964 INFO  LoggingProgressListener   - Progressing 0.0% -- Action UNREDD_ingestion_flow failed (it.geosolutions.geobatch.flow.event.action.ActionException: Error while rasterizing /var/stg_geobatch/temp/ingestionFlow/20150610-144955-007/0_ingestionFlow/unzip/data/forest_cover_2002.shp: Unable to process the input file: Expression NODATA is undefined on line 21, column 15 in gdalrasterize.xml.) [a2f9677d-f73f-4119-9c59-189056f5ff01]
14:50:30,964 ERROR FileBasedEventConsumer    - [pool-6-thread-3] Error during IngestionAction execution: Error while rasterizing /var/stg_geobatch/temp/ingestionFlow/20150610-144955-007/0_ingestionFlow/unzip/data/forest_cover_2002.shp: Unable to process the input file: Expression NODATA is undefined on line 21, column 15 in gdalrasterize.xml.
14:50:30,965 INFO  LoggingProgressListener   - Progressing 100.0% -- Completed [a2f9677d-f73f-4119-9c59-189056f5ff01]
14:50:30,965 INFO  FileBasedEventConsumer    - pool-6-thread-3 DONE!
14:50:30,965 INFO  LoggingProgressListener   - Failed 100.0% -- Completed [a2f9677d-f73f-4119-9c59-189056f5ff01]

**Comment by Damianofds** [comment]
this is related to the admin interface, see https://github.com/slms4redd/admin-interface/issues/58
